from typing import List, Protocol


class EmbeddingError(Exception):
    """Base exception for embedding operations."""
    pass


class EmbeddingDimensionError(EmbeddingError):
    """Raised when the embedding provider returns an unexpected vector dimension."""
    pass


class EmbeddingProviderError(EmbeddingError):
    """Raised when the embedding provider fails or exhausts retry attempts."""
    pass


class EmbeddingService(Protocol):
    """Protocol for provider-agnostic vector embedding generation."""

    async def embed_texts(self, texts: List[str]) -> List[List[float]]:
        """Generate normalized vector embeddings for a list of text strings."""
        ...

    async def embed_query(self, query: str) -> List[float]:
        """Generate normalized vector embedding for a single search query."""
        ...

    @property
    def dimension(self) -> int:
        """The output dimensionality of vectors generated by this service."""
        ...
